### ISSUE TITLE
T-watch-2020 V3 not starting

### ISSUE THREAD

**Issue by darkman7hr** [jeffmer/TTGO-T-watch-2020-Micropython-OS#18]
Hi, 

I uploaded everything like readme says, but:

`MicroPython v1.22.0-preview.21.g4074f828d.dirty on 2023-10-16; Generic ESP32 module with SPIRAM with ESP32
Type "help()" for more information.
>>> import loader
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./loader.py", line 2, in <module>
  File "./tempos.py", line 3, in <module>
  File "./drivers/st7789.py", line 16, in <module>
ValueError: incompatible .mpy file
`

**Comment by jeffmer** [comment]
Hi, it means your cross compiler mpycross is a different version from tte firmware. I have recently put a 1.22 firmware in the repository. Either load the previous firmware 1.19 - and if you do not erase flash, all your uploads should still be there - or update your version of mpycross and reload the mpy files.

**Comment by darkman7hr** [comment]
I'm using 1.22. But I my compiler is:
`bash-5.2# mpy-cross --version
MicroPython v1.20.0 on 2023-05-02; mpy-cross emitting mpy v6.1`

I installed it yesterday. Is there newer?

**Comment by jeffmer** [comment]
I am using the latest software from GitHub which is a preview 1.22?so it would probably be best if you try the 1.19 firmware.

**Comment by darkman7hr** [comment]
with 1.19 firmware I have this problem.. it goes black then it writes "loading.." .. and then nothing.

`+ echo 'Loading mpy files'
Loading mpy files
+ for i in ./*.mpy clocks/*.mpy apps/*.mpy drivers/*.mpy utils/*.mpy fonts/*.mpy
+ mpremote fs cp ./bma_config.mpy :./bma_config.mpy
b"weather : ImportError : no module named 'deflate'\r\ndialclock : AttributeError : 'module' object has no attribute 'getPNG'\r\nstepsdisp : AttributeError : 'module' object has no attribute 'getPNG'\r\n"
Traceback (most recent call last):
  File "/usr/bin/mpremote", line 8, in <module>
    sys.exit(main())
  File "/usr/lib64/python3.9/site-packages/mpremote/main.py", line 528, in main
    handler_func(state, args)
  File "/usr/lib64/python3.9/site-packages/mpremote/commands.py", line 110, in do_filesystem
    state.ensure_raw_repl()
  File "/usr/lib64/python3.9/site-packages/mpremote/main.py", line 470, in ensure_raw_repl
    self.transport.enter_raw_repl(soft_reset=soft_reset)
  File "/usr/lib64/python3.9/site-packages/mpremote/transport_serial.py", line 170, in enter_raw_repl
    raise TransportError("could not enter raw repl")
mpremote.transport.TransportError: could not enter raw repl`

**Comment by jeffmer** [comment]
Looks like the load command is wrong. 

Are you using the install.sh command?

Also using Thonny, you can check which modules have actually been loaded as it has  a view of the ESP32 flash file store.

**Comment by darkman7hr** [comment]
seems I was doing install then load. tnx.

**Comment by ProposeleSS** [comment]
There seems to be an issue: official release version of `mpy-cross` is not compatible with 1.22 
firmware and 1.19 firmware does not have `deflate` module, which causes issues. Easiest solution seems to be to add 1.21 firmware to repo, but I have not tested it yet (can;t find it precompiled, might need to build it myself)

tested on V3 watch

EDIT: found a binary of mpy-cross with required version, and by using it V3 watch works with 1.22 firmware
